server:
  port: ${port:8090}
  servlet:
    context-path: /api/v1
  max-http-header-size: 40MB

spring:
  main:
    allow-bean-definition-overriding: true

  devtools:
    add-properties: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com.example: DEBUG
